syntax = "proto3";


package api;

option go_package = "github.com/keptn/go-utils/pkg/api/oms;oms";


service OmsService {
  rpc GetOrder(GetOrderRequest) returns (GetOrderResponse);

}


message GetOrderRequest {
  string ID = 1;
  int32 Quantity = 2;
}

message GetOrderResponse {
  string ID = 1;
  string CustomerID = 2;
  string Status = 3;
  repeated ItemswithQuantity Items = 4;

}

message ItemswithQuantity {
  string ID = 1;
  int32 Quantity = 2;
}
message GetOrdersResponse {
  repeated GetOrderResponse orders = 1;
}
