syntax = "proto3";

package api;

option go_package = "github.com/OMSV1/common/api;api";

// OmsService defines the gRPC service for the Order Management System (OMS)
service OmsService {
  rpc GetOrder(GetOrderRequest) returns (Order);
  rpc CreateOrder(CreateOrderRequest) returns (Order);
}

// GetOrderRequest represents the request for the GetOrder RPC method
message GetOrderRequest {
  string id = 1;
  int32 quantity = 2;
}


message CreateOrderRequest {
  string customer_id = 1;
  repeated Item items = 2;
}


// GetOrderResponse represents the response for the GetOrder RPC method
message GetOrderResponse {
  string id = 1;
  string customer_id = 2;
  string status = 3;
  repeated ItemswithQuantity items = 4;
}

// ItemswithQuantity represents an item with its quantity in the order
message ItemswithQuantity {
  string id = 1;
  int32 quantity = 2;
}

// Item represents an item in the order
message Item {
  string id = 1;
  string name = 2;
  int32 quantity = 3;
  string price_id = 4;
}

// Order represents an order in the Order Management System (OMS)
message Order {
  string id = 1;
  string customer_id = 2;
  string status = 3;
  repeated Item items = 4;
}
